FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm install --silent
COPY . .
RUN npm run build 
 
FROM nginx:alpine AS final
COPY --from=build /app/dist/devops-quiz/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s CMD wget -qO- http://localhost/ || exit 1
CMD ["nginx", "-g", "daemon off;"]
