apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: devops-quiz
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-south-1:329668418627:certificate/d64de8f6-b753-415b-8655-120d873e93a4"
    alb.ingress.kubernetes.io/healthcheck-path: /api/auth/health
    alb.ingress.kubernetes.io/tags: "Environment=production,Project=devops-quiz"
spec:
  ingressClassName: alb        # ← moved here, removed old annotation
  rules:
  - host: eks.zeba.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: frontend-svc, port: { number: 80 } }
      - path: /api/auth
        pathType: Prefix
        backend:
          service: { name: auth-service, port: { number: 8080 } }
      - path: /api/quiz
        pathType: Prefix
        backend:
          service: { name: quiz-service, port: { number: 8080 } }
      - path: /api/users
        pathType: Prefix
        backend:
          service: { name: user-service, port: { number: 8080 } }