apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-quiz
  labels: { app: frontend }
spec:
  replicas: 2
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
      - name: frontend
        image: 329668418627.dkr.ecr.ap-south-1.amazonaws.com/devops-quiz/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests: { cpu: 50m, memory: 64Mi }
          limits:   { cpu: 200m, memory: 256Mi }
        livenessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: devops-quiz
spec:
  selector: { app: frontend }
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
