apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: devops-quiz
  labels: { app: user-service }
spec:
  replicas: 2
  selector:
    matchLabels: { app: user-service }
  template:
    metadata:
      labels: { app: user-service }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "8080"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
      - name: user-service
        image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/devops-quiz/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef: { name: app-secrets, key: DATABASE_URL }
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef: { name: app-secrets, key: JWT_SECRET }
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        resources:
          requests: { cpu: 100m, memory: 128Mi }
          limits:   { cpu: 500m, memory: 512Mi }
        livenessProbe:
          httpGet: { path: /api/users/health, port: 8080 }
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet: { path: /api/users/health, port: 8080 }
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: devops-quiz
spec:
  selector: { app: user-service }
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
